events {
    worker_connections 1024;
}

http {
    upstream backend_pool {
        # By default this will use Round Robin load balancing
        server web1:8080;
        server web2:8080;
    }

    server {
        listen 80;
        
        location / {
            proxy_pass http://backend_pool;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
